### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by Camnooten** [HyperiumClient/Hyperium-Repo#4]
This is the error I get when I try to launch the game. I know what it means, but maybe you guys could possibly add headers for HTTP requests so that users can download the dependencies. 
``[11:38:58 WARN]: Couldn't download https://hyperium.cc/Hyperium/libs/jxbrowser-linux64-6.19.1.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 403
	at net.minecraft.launcher.updater.PreHashedDownloadable.download(PreHashedDownloadable.java:59) ~[launcher.jar:1.6.84-j]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:109) [launcher.jar:1.6.84-j]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:1.6.84-j]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:86) [launcher.jar:1.6.84-j]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[11:38:58 ERROR]: Gave up trying to download https://hyperium.cc/Hyperium/libs/jxbrowser-linux64-6.19.1.jar for job 'Version & Libraries'
[11:38:58 ERROR]: Job 'Version & Libraries' finished with 2 failure(s)! (took 0:00:01.141)``

**Comment by FalseHonesty** [comment]
Is this no longer an issue?

**Comment by ILYHEART** [comment]
This still is, for myself and several other users
http://prntscr.com/iyllhx
https://media.discordapp.net/attachments/429311217862180867/429322980171186188/unknown.png?width=400&height=228

**Comment by Camnooten** [comment]
I closed it because I am on the old launcher and I thought it didn't work and I was the only one experiencing the issue.

**Comment by Camnooten** [comment]
Should I reopen it?

**Comment by FalseHonesty** [comment]
Yeah, I would @Camnooten. Also, @ILYHEART can I get the entire log please? You can PM it to me on Discord, `FalseHonesty#1337`.

**Comment by Camnooten** [comment]
Not sure. Haven't tried yet, i Will get back to you tomorrow with an update.

**Comment by ChachyGit** [comment]
You have to have the bee launcher for Hyperium

**Comment by ChachyGit** [comment]
New*

**Comment by Sk1er** [comment]
This should be resolved since we have deleted the browser files.
